package com.aayar94.qrscanner.domain.datasource

import com.aayar94.qrscanner.data.local.database.HistoryItemEntity

/** Contract for local QR history storage operations. */
interface ILocalDataSource {

    /** Returns all QR codes scanned by the user. */
    suspend fun getAllScannedHistory(): List<HistoryItemEntity>

    /** Returns all QR codes generated by the user. */
    suspend fun getAllCreatedHistory(): List<HistoryItemEntity>

    suspend fun deleteHistoryItem(historyItemEntity: HistoryItemEntity)
    suspend fun insertHistoryItem(historyItemEntity: HistoryItemEntity)

}